# /wordpress-docker/docker-compose.yml
---
version: "3.9"
services:
  db:
    container_name: "local-wordpress-db"
    image: "mysql:8.4"
    restart: unless-stopped
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=wordpress_user
      - PMA_PASSWORD=wordpress_password
    depends_on:
      - db

  wordpress:
    container_name: "local-wordpress"
    depends_on:
      - db
    image: "wordpress:latest"
    ports:
      - "3000:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./themes:/var/www/html/wp-content/themes"
      - "./plugins:/var/www/html/wp-content/plugins"
# Volumes
volumes:
  mysql_data:
